### ISSUE TITLE
The current week of calender is not showing

### ISSUE THREAD

**Issue by Renkon117** [pedrohff/flutter_heatmap_calendar#2]
the very recent week is not mapping and filing the color when it's updated, like one whole week is not showing up in very right side of the calendar.

I will appreciate any suggestions please.

**Comment by IGMendoza** [comment]
A workaround:
In the files: 
week_columns.dart line 98, change to: 
    DateTime today = DateTime.now().add(Duration(days: 7));

time_utils.dart line 33, change to:
    DateTime today = DateTime.now().add(Duration(days: 7));

will try to do a pull request with this. seems to fix the issue

**Comment by IGMendoza** [comment]
Actually, @pedrohff  fixed it in his newest commit. The issue now is that when adding to the pubsec.yaml the "heatmap_calendar: ^1.2.5"  it is not recognizing version 1.2.6 so it is not installing that one

**Comment by pedrohff** [comment]
It's not correctly tagged? I'll check this out later

**Comment by pedrohff** [comment]
@Renkon117 @IGMendoza I've just tagged it correctly, whenever you guys can please check if it's OK

**Comment by IGMendoza** [comment]
yup, its ok now, thanks!
